version: '3.5'
services:
  web-shell:
    container_name: web-shell
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    tty: true
    restart: unless-stopped
    command: yarn start
    volumes:
    - ./:/app
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "10000:3000"